### ISSUE TITLE
Please make $client in Client.php protected instead of private.

### ISSUE THREAD

**Issue by cmanley** [datto/php-json-rpc-http#2]
So that one can create child classes with custom method(s).

**Comment by smortensen** [comment]
Hi Craig,

I'd like to discuss this more, but there's a bit of time zone difference between us. (I'm in the GMT -4 hour time zone.) Would you potentially be available for a phone conversation someday in the evening? I can be available around 6-7 pm your time. Is that too late for you?

~Spencer

**Comment by cmanley** [comment]
Hi Spencer, that's no problem. I sent you an email.

**Comment by smortensen** [comment]
Thank you! I'll look for you. I'll try to get in touch with you sometime this week.

**Comment by smortensen** [comment]
This is a very old issue; I'm closing it for housekeeping reasons. I never did get a sense of exactly what custom methods were desired. If I had had a better understanding of the needs of the poster, then I think we would have gotten somewhere.
