### ISSUE TITLE
It does not throw errors when it has connection issues. it just returns null

### ISSUE THREAD

**Issue by tummybos** [datto/php-json-rpc-http#4]
I wouldn't know if connection failed

**Comment by smortensen** [comment]
All you know is that the connection failed, but there's no explanation about the reason for the failure. That _does_ make it hard to get useful feedback about the connection failure.

So! We need the HTTP response headers. We can use that information to construct a useful exception object.

Those HTTP response headers are readily available through the CURL library, but PHP can be compiled _without_ CURL. This little Composer library works for _everyone_, so we'll need to find a way with broader support.

Here's one idea:
```php
$response = file_get_contents('http://google.com');

echo "response: ", var_export($response, true), "\n";
echo "headers: ", json_encode($http_response_header), "\n";
```

How about that? Would that work?

We'd need to extract the HTTP status code (and any other useful information) from the headers, and then construct the exception.

Is this something you could build for us?

**Comment by smortensen** [comment]
All right! A new version (4.0.1) is out--with full reporting for connection issues!
