### ISSUE TITLE
Erase blank please.

### ISSUE THREAD

**Issue by nickppbd** [datto/php-json-rpc-http#5]
`composer require "datto/json-rpc-http": "~4.0"`
it's not working.

`composer require "datto/json-rpc-http":"~4.0"`
it's working.

I don't know the reason.

**Comment by smortensen** [comment]
Hmm! Sorry for the trouble.

I've updated the README:
https://github.com/datto/php-json-rpc-http/commit/563bd004ce281a467b3f55f10a54860afa472923

It turns out you can omit that colon altogether!

And thank you for reporting this. I'm sure you saved a lot of people a good deal of frustration.
