### ISSUE TITLE
Examples not running

### ISSUE THREAD

**Issue by zerocarbthirty** [datto/php-json-rpc-http#6]
Howdy, I am playing around with php-json-rpc-http and trying to get the examples to work.

If I run it as-is in the release:

php clientValidCredentials.php
PHP Warning:  require(/home/vendor/autoload.php): failed to open stream: No such file or directory

I think that may be because the include in the example is sort of nested:

require dirname(dirname(__DIR__)) . '/vendor/autoload.php';

if I change that so that it's similar to regular autoload commands with composer:

require __DIR__ . '/vendor/autoload.php';

php clientValidCredentials.php
PHP Fatal error:  Uncaught Error: Class 'Datto\JsonRpc\Http\Examples\Authenticated\Client' not found

I installed it using composer.

**Comment by smortensen** [comment]
Okay! I've made the examples much easier to run. Thank you for raising the issue.

**Comment by BeholdersEye** [comment]
Sorry to necro this but "I've made the examples much easier to run" is not very helpful either. Apparently they are not easy enough.

Is it possible to install this library without using composer or not?

Quoth the documentation:

"Installation

If you're using Composer, you can include this library (datto/json-rpc-http) like this:"

Seems like it's not but maybe you can engineer some way to get your code to run without Composer. It would be a good idea to mention it in the installation documentation.
