### ISSUE TITLE
CONTENT_TYPE include utf8

### ISSUE THREAD

**Issue by twocolors** [datto/php-json-rpc-http#7]
if ct have "application/json; charset=utf8", not catch plz fix
`if (!isset($_SERVER['CONTENT_TYPE']) || (strpos(strtolower($_SERVER['CONTENT_TYPE']), self::$CONTENT_TYPE) === false)) {
            self::errorInvalidContentType();
        }`

**Comment by smortensen** [comment]
All right, the fix just went out in the 5.0.4 release! Let me know if you need anything else.
