### ISSUE TITLE
support  catch replay on "ob_start"

### ISSUE THREAD

**Issue by twocolors** [datto/php-json-rpc-http#9]
hi, mb make support catch output on reply like

```
ob_start();
parent::reply();
$reply = ob_get_contents();
ob_end_clean();
```

to do this replace `exit()` to `return`

**Comment by smortensen** [comment]
All right, I've made the change:
https://github.com/datto/php-json-rpc-http/commit/db15a075f3562c4e8d297b9082acc5b2869bd4b4

Is that better?

**Comment by twocolors** [comment]
thx
